name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'

      - name: Flutter & Dart versions
        run: flutter --version && dart --version

      - name: Pub get (root)
        run: flutter pub get

      - name: Format check
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze

      - name: Get example deps
        working-directory: example
        run: flutter pub get

      # Build the Android example (assembleDebug) to catch plugin issues.
      - name: Build example (Android)
        working-directory: example
        run: flutter build apk --debug